# semopy quickstart

This notebook should be treated as a secondanary (at best) source of information on the **semopy** usage. For a more throughout description of the package, visit the [Tutorial section](https://semopy.com/tutorial.html) of the website.

## Fitting SEM models to data

**semopy**'s pilestones are model classes, namely:
1. `Model` - a regular SEM model you'd expect to meet in other SEM/CFA software.
2. `ModelMeans` - same as `Model`, but it can model variables means and treats exogenous observed variables as fixed effects (i.e. they reside together with means in the models meanstructure).
3. `ModelEffects` - an extension of `ModelMeans` that can take population structure into an account by introducing random effects into the model. It can be thought as a generalization of LMMs to SEM.

One should feed the description of a model in text form to constructors of those classes, and then invoke the `fit` method. The text description uses similar syntax to that which is popular to describe linear models in R. If you've used **lavaan**, you'd certainly find it very familiar. See the [Syntax and constraints](https://semopy.com/syntax.html) subsection of the tutorial for more details.

For example, let's assume that SEM model we want to work with is just a multivariate regression:

$$ y = x_1 + x_2 + x_3 + \epsilon$$

In **semopy** syntax it is:

In [1]:
from semopy.examples import multivariate_regression
desc = multivariate_regression.get_model()
print(desc)

y ~ x1 + x2 + x3

Now, let's instantiate a `Model` object:

In [2]:
from semopy import Model
m = Model(desc)

Then we'd like to fit the `Model` to data. We will use data that is provided by **semopy** package together with `multivariate_regression` toy model:

In [3]:
data = multivariate_regression.get_data()
data.head()

         x1    x2        x3           y
0 -2.770831   3.0 -1.321214   24.794079
1  0.898572   6.0  1.350755   23.583808
2  2.900707  18.0  0.286264  111.938996
3  2.640530  12.0 -0.749681   85.247063
4  0.066051  12.0  0.077528   71.436439

Now, we estimate parameters and print optimizer result (to see if everything is OK):

In [4]:
r = m.fit(data)
print(r)

Name of objective: MLW
Optimization method: SLSQP
Optimization successful.
Optimization terminated successfully
Objective value: 0.000
Number of iterations: 73
Params: 1.943 6.037 -9.769 1.022

All models are equipped with the `inspect` method. It is the most useful method you'd find in **semopy**, actually! It outputs parameters estimates in a fancy pandas DataFrame:

In [5]:
ins = m.inspect()
ins

  lval  op rval  Estimate  Std. Err     z-value       p-value
0    y   ~   x1  1.942880  0.057089   34.032650  0.000000e+00
1    y   ~   x2  6.037344  0.016435  367.338353  0.000000e+00
2    y   ~   x3 -9.769120  0.104997  -93.041822  0.000000e+00
3    y  ~~    y  1.022255  0.144569    7.071068  1.537437e-12

Okay, that was quiet a simple model. Let's augment it a bit by introducing an extra relationship between $x_3$ and $x_2$:

In [6]:
desc += '\nx3 ~ x2'
print(desc)

y ~ x1 + x2 + x3
x3 ~ x2

I'll be honest: when I was generating data for this simple multivariate regression model, I didn't took that extra relationship into an account. So it makes no sense. We'd expect that this lack of sense will be reported by **semopy**:

In [7]:
m = Model(desc)
m.fit(data)
ins = m.inspect()
ins

  lval  op rval  Estimate  Std. Err     z-value       p-value
0   x3   ~   x2 -0.006254  0.015642   -0.399817  6.892917e-01
1    y   ~   x1  1.943154  0.057006   34.086577  0.000000e+00
2    y   ~   x2  6.037404  0.016441  367.219881  0.000000e+00
3    y   ~   x3 -9.769318  0.104863  -93.162562  0.000000e+00
4   x3  ~~   x3  0.930036  0.131527    7.071068  1.537437e-12
5    y  ~~    y  1.022693  0.144631    7.071068  1.537437e-12

See how p-values of this new relationship is very high (and the estimate is close to zero). That's there is no way this new relationship fits the data well.


The power of SEM lies in it's ability to model latent variables. There a few of ways to specify them in **semopy**, but the most straightforward one is to use the measurement operator =~. See how it's done in a classical "Political Democracy" model:

In [8]:
from semopy.examples import political_democracy
desc = political_democracy.get_model()
data = political_democracy.get_data()
print(desc)
data.head()

# measurement model
ind60 =~ x1 + x2 + x3
dem60 =~ y1 + y2 + y3 + y4
dem65 =~ y5 + y6 + y7 + y8
# regressions
dem60 ~ ind60
dem65 ~ ind60 + dem60
# residual correlations
y1 ~~ y5
y2 ~~ y4 + y6
y3 ~~ y7
y4 ~~ y8
y6 ~~ y8

,y1,y2,y3,y4,y5,y6,y7,y8,x1,x2,x3
1,2.50,0.000000,3.333333,0.000000,1.250000,0.000000,3.726360,3.333333,4.442651,3.637586,2.557615
2,1.25,0.000000,3.333333,0.000000,6.250000,1.100000,6.666666,0.736999,5.384495,5.062595,3.568079
3,7.50,8.800000,9.999998,9.199991,8.750000,8.094061,9.999998,8.211809,5.961005,6.255750,5.224433
4,8.90,8.800000,9.999998,9.199991,8.907948,8.127979,9.999998,4.615086,6.285998,7.567863,6.267495
5,10.00,3.333333,9.999998,6.666666,7.500000,3.333333,9.999998,6.666666,5.863631,6.818924,4.573679

In [9]:
m = Model(desc)
m.fit(data)
ins = m.inspect()
ins

     lval  op   rval  Estimate  Std. Err    z-value   p-value
0   dem60   ~  ind60  1.482379  0.399024   3.715017  0.000203
1   dem65   ~  ind60  0.571912  0.221383   2.583364  0.009784
2   dem65   ~  dem60  0.837574  0.098446   8.507992       0.0
3      x1   ~  ind60  1.000000         -          -         -
4      x2   ~  ind60  2.180494  0.138565  15.736254       0.0
5      x3   ~  ind60  1.818546  0.151993   11.96465       0.0
6      y1   ~  dem60  1.000000         -          -         -
7      y2   ~  dem60  1.256819  0.182687   6.879647       0.0
8      y3   ~  dem60  1.058174  0.151521   6.983699       0.0
9      y4   ~  dem60  1.265186  0.145151   8.716344       0.0
10     y5   ~  dem65  1.000000         -          -         -
11     y6   ~  dem65  1.185743  0.168908   7.020032       0.0
12     y7   ~  dem65  1.279717  0.159996    7.99841       0.0
13     y8   ~  dem65  1.266084  0.158238   8.001141       0.0
14  dem65  ~~  dem65  0.172210  0.214861   0.801494  0.422846
15  dem60  ~~  dem60  3.950849  0.920451   4.292296  0.000018
16  ind60  ~~  ind60  0.448321  0.086677   5.172345       0.0
17     y1  ~~     y5  0.624423  0.358435   1.742083  0.081494
18     y1  ~~     y1  1.892743   0.44456   4.257565  0.000021
19     y2  ~~     y4  1.319589   0.70268   1.877937   0.06039
20     y2  ~~     y6  2.156164  0.734155   2.936934  0.003315
21     y2  ~~     y2  7.385292  1.375671   5.368501       0.0
22     y3  ~~     y7  0.793329  0.607642   1.305585  0.191694
23     y3  ~~     y3  5.066628  0.951722   5.323646       0.0
24     y4  ~~     y8  0.347222  0.442234   0.785154  0.432363
25     y4  ~~     y4  3.147911  0.738841   4.260605   0.00002
26     y6  ~~     y8  1.357037    0.5685   2.387047  0.016984
27     y6  ~~     y6  4.954364  0.914284   5.418843       0.0
28     x1  ~~     x1  0.081573  0.019495   4.184317  0.000029
29     y8  ~~     y8  3.256389   0.69504   4.685182  0.000003
30     x2  ~~     x2  0.119894  0.069747   1.718973  0.085619
31     y7  ~~     y7  3.430032  0.712732   4.812512  0.000001
32     y5  ~~     y5  2.351910  0.480369   4.896044  0.000001
33     x3  ~~     x3  0.466732  0.090168   5.176276       0.0

## Estimating intercepts
There are 2 ways to estimate intercepts (or means) in **semopy**.

The first one, is to use `estimate_means` function on the fitted `Model`:

In [10]:
from semopy import estimate_means
means = estimate_means(m)
means

   lval op rval  Estimate  Std. Err   z-value       p-value
0    x1  ~    1  5.054383  0.727938  6.943425  3.827161e-12
1    x2  ~    1  4.792193  1.500487  3.193760  1.404330e-03
2    x3  ~    1  3.557689  1.396202  2.548119  1.083054e-02
3    y1  ~    1  5.464666  2.613189  2.091187  3.651131e-02
4    y2  ~    1  4.256439  3.896433  1.092394  2.746600e-01
5    y3  ~    1  6.563108  3.254787  2.016448  4.375315e-02
6    y4  ~    1  4.452532  3.323998  1.339511  1.804044e-01
7    y5  ~    1  5.136250  2.601964  1.973990  4.838287e-02
8    y6  ~    1  2.978071  3.341622  0.891205  3.728191e-01
9    y7  ~    1  6.196263  3.265850  1.897289  5.778977e-02
10   y8  ~    1  4.043386  3.215399  1.257507  2.085702e-01

This method, however, is not very reliable in the sense that one should not trust p-values.

The second, and the most appopriate aproach, is to use `ModelMeans`:

In [11]:
from semopy import ModelMeans
m = ModelMeans(desc)
m.fit(data)
m.inspect()

     lval  op   rval  Estimate  Std. Err    z-value   p-value
0   dem60   ~  ind60  1.482999  0.399149   3.715401  0.000203
1   dem65   ~  ind60  0.572322  0.221313   2.586027  0.009709
2   dem65   ~  dem60  0.837346  0.098351   8.513859       0.0
3      x1   ~  ind60  1.000000         -          -         -
4      x2   ~  ind60  2.180375   0.13851  15.741609       0.0
5      x3   ~  ind60  1.818522   0.15196  11.967144       0.0
6      y1   ~  dem60  1.000000         -          -         -
7      y2   ~  dem60  1.256753  0.182439   6.888611       0.0
8      y3   ~  dem60  1.057746  0.151385   6.987136       0.0
9      y4   ~  dem60  1.264790  0.145006   8.722314       0.0
10     y5   ~  dem65  1.000000         -          -         -
11     y6   ~  dem65  1.185687   0.16881   7.023806       0.0
12     y7   ~  dem65  1.279531  0.159903   8.001935       0.0
13     y8   ~  dem65  1.265935   0.15811    8.00667       0.0
14     x1   ~      1  5.054393  0.084062  60.126661       0.0
15     x2   ~      1  4.792218   0.17327  27.657545       0.0
16     x3   ~      1  3.557715  0.161233  22.065738       0.0
17     y1   ~      1  5.464665  0.301854   18.10368       0.0
18     y2   ~      1  4.256439   0.44987   9.461478       0.0
19     y3   ~      1  6.563146  0.375891  17.460248       0.0
20     y4   ~      1  4.452537   0.38391  11.597855       0.0
21     y5   ~      1  5.136254  0.300511  17.091727       0.0
22     y6   ~      1  2.978057  0.385931   7.716551       0.0
23     y7   ~      1  6.196289  0.377202  16.426972       0.0
24     y8   ~      1  4.043383  0.371319  10.889254       0.0
25  dem65  ~~  dem65  0.172487  0.214803   0.803001  0.421974
26  dem60  ~~  dem60  3.956039  0.921185   4.294508  0.000018
27  ind60  ~~  ind60  0.448436  0.086692   5.172765       0.0
28     y1  ~~     y5  0.623671  0.358319   1.740548  0.081763
29     y1  ~~     y1  1.891402  0.444423   4.255861  0.000021
30     y2  ~~     y4  1.313085   0.70198   1.870545  0.061408
31     y2  ~~     y6  2.152828  0.733771   2.933925  0.003347
32     y2  ~~     y2  7.372791  1.373882   5.366395       0.0
33     y3  ~~     y7  0.794961  0.607702   1.308143  0.190825
34     y3  ~~     y3  5.067487  0.951738   5.324453       0.0
35     y4  ~~     y8  0.348246  0.442238   0.787464   0.43101
36     y4  ~~     y4  3.147907  0.738783   4.260936   0.00002
37     y6  ~~     y8  1.356165  0.568281   2.386434  0.017013
38     y6  ~~     y6  4.953952  0.914241   5.418647       0.0
39     x1  ~~     x1  0.081551   0.01949   4.184259  0.000029
40     y8  ~~     y8  3.254068  0.694596   4.684837  0.000003
41     x2  ~~     x2  0.119802  0.069721   1.718314  0.085739
42     y7  ~~     y7  3.431334  0.712843   4.813589  0.000001
43     y5  ~~     y5  2.350969  0.480238   4.895427  0.000001
44     x3  ~~     x3  0.466708  0.090157   5.176583       0.0

In both cases, intercepts are specified by "variable ~ 1".

## Groups

It is a very common case that data is stratified. For example, in Holzinger39 dataset, there is a "school" column that is good candidate for a group variable.
Again, there are two ways to take grouped data in account. The first one is to just subtract group-wise means from the data. It is done this way:

In [12]:
from semopy.examples import holzinger39
desc, data = holzinger39.get_model(), holzinger39.get_data()
print(desc)
data.head()

visual =~ x1 + x2 + x3
textual =~ x4 + x5 + x6
speed =~ x7 + x8 + x9

,id,sex,ageyr,agemo,school,grade,x1,x2,x3,x4,x5,x6,x7,x8,x9
1,1,1,13,1,Pasteur,7.0,3.333333,7.75,0.375,2.333333,5.75,1.285714,3.391304,5.75,6.361111
2,2,2,13,7,Pasteur,7.0,5.333333,5.25,2.125,1.666667,3.00,1.285714,3.782609,6.25,7.916667
3,3,2,13,1,Pasteur,7.0,4.500000,5.25,1.875,1.000000,1.75,0.428571,3.260870,3.90,4.416667
4,4,1,13,2,Pasteur,7.0,5.333333,7.75,3.000,2.666667,4.50,2.428571,3.000000,5.30,4.861111
5,5,2,12,2,Pasteur,7.0,4.833333,4.75,0.875,2.666667,4.00,2.571429,3.695652,6.30,5.916667

In [13]:
m = Model(desc)
m.fit(data, groups=['school'])
ins = m.inspect()
ins[ins.op == '~']

  lval op     rval  Estimate  Std. Err    z-value p-value
0   x1  ~   visual  1.000000         -          -       -
1   x2  ~   visual  0.590873  0.101308   5.832431     0.0
2   x3  ~   visual  0.780678  0.110267    7.07992     0.0
3   x4  ~  textual  1.000000         -          -       -
4   x5  ~  textual  1.088184  0.067248  16.181653     0.0
5   x6  ~  textual  0.914085  0.057407  15.922923     0.0
6   x7  ~    speed  1.000000         -          -       -
7   x8  ~    speed  1.185279  0.162349   7.300832     0.0
8   x9  ~    speed  1.062353  0.145981   7.277316     0.0

Or, you can use `ModelEffects` in a LMM-fashion:

In [14]:
from semopy import ModelEffects
# Notice the intercepts=False. It disables intercepts in the model.
# The same is appliable to ModelMeans, by the way.
m = ModelEffects(desc, intercepts=False)
m.fit(data, group='school')
ins = m.inspect()
ins[ins.op == '~']

  lval op     rval  Estimate  Std. Err    z-value p-value
0   x1  ~   visual  1.000000         -          -       -
1   x2  ~   visual  0.669629  0.114406   5.853109     0.0
2   x3  ~   visual  0.706306  0.106458   6.634579     0.0
3   x4  ~  textual  1.000000         -          -       -
4   x5  ~  textual  1.101798  0.075573   14.57929     0.0
5   x6  ~  textual  0.898198  0.063037  14.248829     0.0
6   x7  ~    speed  1.000000         -          -       -
7   x8  ~    speed  1.241414   0.17258   7.193275     0.0
8   x9  ~    speed  1.272017  0.176266   7.216446     0.0

## Prediction of factor scores
**semopy** can predict latent factor scores by invoking `predict_factors` method:

In [15]:
desc = political_democracy.get_model()
data = political_democracy.get_data()
m = Model(desc)
m.fit(data)
factors = m.predict_factors(data)
# We are centering factor estimates because Model doesn't have intercepts
# and it is usually asssumed that latent variables have zero mean.
# If we used ModelMeans, that would be unnecessary.
factors -= factors.mean()
factors.head()

      dem60     dem65     ind60
0 -2.539528 -2.368729 -0.536216
1 -2.345362 -1.513466  0.151093
2  2.925690  2.998107  0.740218
3  2.883632  3.021921  1.244115
4  2.428383  2.422393  0.831255

## Prediction of output dependent variables by exogenous
After fitting the model, we might want to predict certain output (i.e. variables that don't have arrows pointing from them) variables. In one special case, it is possible to do it blazzingly fast: if we know all or some of the exogenous variables. For example, in case of the multivariate regression, the output variable is $y$ and exogenous variables are $x_1, x_2, x_3$. `ModelMeans`, `ModelEffects` can do it efficiently by *predict_exo* method:

In [16]:
desc = multivariate_regression.get_model()
data = multivariate_regression.get_data()
data_test = data.iloc[-5:]
data_train = data.iloc[:-5]
m = ModelMeans(desc)
m.fit(data)
preds = m.predict_exo(data_test.drop(['y'], axis=1))
print('Mean relative error: {:.3f}%'.format(
      abs((preds['y'].values - data_test['y'].values) / data_test['y'].values).mean() * 100))

Mean relative error: 1.041%

## Generalized prediction and/or imputation
Actually, you can "predict" any data given... any other data. You can have arbitrary misses in the data, or even you can lack certain variables, but we can still try to predict/impute those misses and variables using `predict` method. It is available for models in **semopy**. Let's see it on the Political Democracy example:

In [17]:
import numpy as np
np.random.seed(1)
desc = political_democracy.get_model()
data = political_democracy.get_data()
m = Model(desc)

# Let's generate random misses in data:
N_misses = 5
mask_x = np.random.randint(0, len(data), N_misses)
mask_y = np.random.randint(0, len(data.columns), N_misses)
data_true = data.values[mask_x, mask_y].copy()
data.values[mask_x, mask_y] = np.nan
# Model can work with misses by default, but ModelMeans and ModelEffects can not. However, there is
# a FIML estimator available (just FYI).
m.fit(data)
pred = m.predict(data)
print('Mean relative error: {:.3f}%'.format(
       abs((pred.values[mask_x, mask_y] - data_true) / data_true).mean() * 100))
pred.head()

Mean relative error: 7.634%

,x1,x2,x3,y1,y2,y3,y4,y5,y6,y7,y8,dem60,dem65,ind60
1,4.442651,3.637586,2.557615,2.50,0.000000,3.333333,0.000000,1.250000,0.000000,3.726360,3.333333,1.527814,2.402259,2.097229
2,5.384495,5.062595,3.568079,1.25,0.000000,3.333333,0.000000,6.250000,1.100000,6.666666,0.736999,1.727005,3.335360,2.785104
3,5.961005,6.255750,5.224433,7.50,8.800000,9.999998,9.199991,8.750000,8.094061,9.999998,8.211809,7.077607,7.814884,3.370078
4,6.285998,7.567863,6.267495,8.90,8.800000,9.999998,9.199991,8.907948,8.127979,9.999998,4.615086,7.094697,7.903726,3.875785
5,5.863631,6.818924,4.573679,10.00,3.333333,9.999998,6.666666,7.500000,3.333333,9.999998,6.666666,6.590319,7.239787,3.464230

However, I recommend to be cautuios with this imputation method as I haven't studied well it's performance. Sometimes it is horrible, especially when imputation itself is ambiguous.

## Visualizing SEM models

As a fun trick, you can visualize SEM models using the **graphviz** library. See:

In [26]:
from semopy import semplot
g = semplot(m, filename='t.pdf')
g

Notice that you can edit *g* manually to fit your needs if you know the dot-language:

In [19]:
print(g)

digraph G {
	overlap=scale splines=true
	edge [fontsize=12]
	node [fillcolor="#cae6df" shape=circle style=filled]
	ind60 [label=ind60]
	dem60 [label=dem60]
	dem65 [label=dem65]
	node [shape=box style=""]
	x1 [label=x1]
	x2 [label=x2]
	x3 [label=x3]
	y1 [label=y1]
	y2 [label=y2]
	y3 [label=y3]
	y4 [label=y4]
	y5 [label=y5]
	y6 [label=y6]
	y7 [label=y7]
	y8 [label=y8]
	ind60 -> dem60 [label="1.461\np-val: 0.00"]
	ind60 -> dem65 [label="0.625\np-val: 0.00"]
	dem60 -> dem65 [label="0.818\np-val: 0.00"]
	ind60 -> x1 [label=1.000]
	ind60 -> x2 [label="2.185\np-val: 0.00"]
	ind60 -> x3 [label="1.819\np-val: 0.00"]
	dem60 -> y1 [label=1.000]
	dem60 -> y2 [label="1.249\np-val: 0.00"]
	dem60 -> y3 [label="1.042\np-val: 0.00"]
	dem60 -> y4 [label="1.246\np-val: 0.00"]
	dem65 -> y5 [label=1.000]
	dem65 -> y6 [label="1.187\np-val: 0.00"]
	dem65 -> y7 [label="1.297\np-val: 0.00"]
	dem65 -> y8 [label="1.215\np-val: 0.00"]
}

## Fit indices
**semopy** has some of the popular fit indices that researcher can examine to better understand his SEM model:

In [20]:
from semopy import calc_stats
calc_stats(m)

,DoF,DoF Baseline,chi2,chi2 p-value,chi2 Baseline,CFI,GFI,AGFI,NFI,TLI,RMSEA,AIC,BIC,LogLik
Value,35,55,42.937843,0.167616,733.810537,0.988306,0.941486,0.90805,0.941486,0.981624,0.055361,60.854991,132.697122,0.572505

## Robust standard errors
It is a common practice to use apply Huber-White correction to standard errors estimation. Whether it is a reasonable practice, [is debatable](https://www.tandfonline.com/doi/abs/10.1080/10705510701758091?scroll=top&needAccess=true&journalCode=hsem20), yet **semopy** provides such a functionality for a user's discretion via `se_robust` to the `inspect` method:

In [21]:
desc = political_democracy.get_model()
data = political_democracy.get_data()
m = Model(desc)
m.fit(data)
robust = m.inspect(se_robust=True)
robust

     lval  op   rval  Estimate  Std. Err    z-value   p-value
0   dem60   ~  ind60  1.482379  0.337907   4.386943  0.000011
1   dem65   ~  ind60  0.571912  0.206258     2.7728  0.005558
2   dem65   ~  dem60  0.837574  0.086515   9.681209       0.0
3      x1   ~  ind60  1.000000         -          -         -
4      x2   ~  ind60  2.180494  0.143633  15.181011       0.0
5      x3   ~  ind60  1.818546  0.139171  13.066974       0.0
6      y1   ~  dem60  1.000000         -          -         -
7      y2   ~  dem60  1.256819  0.140327   8.956363       0.0
8      y3   ~  dem60  1.058174   0.13435   7.876242       0.0
9      y4   ~  dem60  1.265186   0.12698   9.963697       0.0
10     y5   ~  dem65  1.000000         -          -         -
11     y6   ~  dem65  1.185743  0.171319   6.921259       0.0
12     y7   ~  dem65  1.279717  0.166451   7.688236       0.0
13     y8   ~  dem65  1.266084  0.171247   7.393321       0.0
14  dem65  ~~  dem65  0.172210   0.22019   0.782096  0.434158
15  dem60  ~~  dem60  3.950849  0.869781   4.542348  0.000006
16  ind60  ~~  ind60  0.448321  0.072456   6.187479       0.0
17     y1  ~~     y5  0.624423  0.418701   1.491334  0.135874
18     y1  ~~     y1  1.892743  0.410137     4.6149  0.000004
19     y2  ~~     y4  1.319589  0.741365   1.779944  0.075085
20     y2  ~~     y6  2.156164  0.875862   2.461761  0.013826
21     y2  ~~     y2  7.385292  1.303527   5.665625       0.0
22     y3  ~~     y7  0.793329  0.581796   1.363585  0.172698
23     y3  ~~     y3  5.066628   0.99662    5.08381       0.0
24     y4  ~~     y8  0.347222  0.393582   0.882208  0.377664
25     y4  ~~     y4  3.147911  0.776549   4.053716   0.00005
26     y6  ~~     y8  1.357037  0.729689   1.859745  0.062922
27     y6  ~~     y6  4.954364  0.967886   5.118746       0.0
28     x1  ~~     x1  0.081573  0.018039   4.522072  0.000006
29     y8  ~~     y8  3.256389  0.849813   3.831887  0.000127
30     x2  ~~     x2  0.119894  0.072657   1.650127  0.098917
31     y7  ~~     y7  3.430032  0.586614   5.847171       0.0
32     y5  ~~     y5  2.351910  0.561731   4.186896  0.000028
33     x3  ~~     x3  0.466732  0.085707   5.445643       0.0

## Random effects
Remember `ModelEffects`? Actually, it is true purpose is not modeling grouped data, but modeling the so-called random effects. It is really helpful in case where we know covariance matrix of residuals. It is mostly used in GWAS where such a covariance matrix is usually a matrix of genetic kinship between individuals.

Next, we are going to construct artifical model with such a covariance matrix *K* known, and then we are going to fit to the generated data:

In [22]:
import pandas as pd
np.random.seed(1)
n = 100 # Number of data samples
p = 3 # Number of indicators per latent factor
# Generating random parameters
params = [np.random.uniform(0.2, 1.2, size=(p - 1, 1)),
          np.random.uniform(0.2, 1.2, size=(p -1, 1))]
params = list(map(lambda x: np.append([1], x), params))
y = np.random.normal(size=(n, 2 * p))
# Generating factor scores
eta1 = np.random.normal(scale=1, size=(n, 1))
eta2 = np.random.normal(scale=1, size=(n, 1)) + 3 * eta1
# Loading factors onto indicators
y[:, :p] += np.kron(params[0], eta1)
y[:, p:] += np.kron(params[1], eta2)

# Intercepts!
means = np.random.normal(scale=3, size=2 * p)
y += means
params.append(means)

# Finally, random effects are here. They mess the data and there is nothing we could do...
u = np.random.normal(scale=3, size=y.shape)
y += u
# Unless we magically know the covariance matrix of those random effects!
k = u @ u.T
res = list()
d = {'eta1': list(), 'eta2': list()}
y_names = list()
for i in range(1, p + 1):
    res.append((f'y{i}', '~', 'eta1', params[0][i - 1]))
    res.append((f'y{i}', '~', '1', params[2][i - 1]))
    y_names.append(res[-1][0])
    d['eta1'].append(y_names[-1])
for j in range(1, p + 1):
    res.append((f'y{j + i}', '~', 'eta2', params[1][j - 1]))
    res.append((f'y{j + i}', '~', '1', params[2][i + j - 1]))
    y_names.append(res[-1][0])
    d['eta2'].append(y_names[-1])
desc = '\n'.join(f"{eta} =~ {' + '.join(ys)}" for eta, ys in d.items())
desc += '\neta2 ~ eta1'
params = pd.DataFrame.from_records(res, columns=['lval', 'op', 'rval', 'est'])
data = pd.DataFrame(np.append(np.append(y, eta1, axis=1), eta2, axis=1),
                    columns=y_names + ['eta1', 'eta2'])
data = data.drop(['eta1', 'eta2'], axis=1)
data['group'] = data.index

print(desc)
data.head()

eta1 =~ y1 + y2 + y3
eta2 =~ y4 + y5 + y6
eta2 ~ eta1

         y1        y2        y3        y4        y5        y6  group
0 -5.245105  2.541163 -1.995541 -9.116109 -0.708878  1.638819      0
1  2.579171 -0.296283  4.165746 -3.551921 -3.588691  5.024555      1
2 -3.652643  0.083678 -2.161153 -8.495831 -6.401319  3.464854      2
3 -4.290240  1.736493  0.095633 -3.534592 -1.230620  5.820926      3
4 -4.274387 -0.845491 -0.673557  2.267882 -4.332353  5.565805      4

The *group* column is not important in this particular case and is just needed to feed it to `ModelEffects`. It is possible that observations have a common "group" (like schools in the previous example with Holzinger-Swineford 1939). 
Now, before we actually try out the `ModelEffects`, let's see how well `ModelMeans` handles the situation:

In [23]:
m = ModelMeans(desc)
m.fit(data)
ins = m.inspect()
errs = list()
for _, row in params.iterrows():
    t = (ins['op'] == row['op']) & (ins['lval'] == row['lval']) &\
        (ins['rval'] == row['rval'])
    t = ins[t]
    est = t['Estimate'].values[0]
    errs.append(abs((est - row['est']) / row['est']))
err = np.mean(errs)
print("Mean relative error: {:.3f}%".format(err * 100))

Mean relative error: 48.069%

Not a great result. Let's now see if we can improve upon it by employing the `ModelEffects`:

In [24]:
m = ModelEffects(desc)
m.fit(data, group='group', k=k)
ins = m.inspect()
errs = list()
for _, row in params.iterrows():
    t = (ins['op'] == row['op']) & (ins['lval'] == row['lval']) &\
        (ins['rval'] == row['rval'])
    t = ins[t]
    est = t['Estimate'].values[0]
    errs.append(abs((est - row['est']) / row['est']))
err = np.mean(errs)
print("Mean relative error: {:.3f}%".format(err * 100))

Mean relative error: 14.392%

That's definitely better.

## Objective functions
**semopy** models have a variety of objective functions at user's disposal. You can select them by feeding the `obj` argument to the `fit` method. Here is the list of available objectives for each of the models (the first ones are the default ones):

- `Model`
1. `'MLW'` - Wishart Maximum Likelihood;
2. `'ULS'` - Unweighted Least Squares;
3. `'GLS'`- Generalized Least Squares;
4. `'FIML'` - Full Information Maximum Likelihood.
Take a note that `Model` handles missing data for all of the functions above, as 1-3 fit model to a covariance matrix that is calculated taking missing data into an account.
- `ModelMeans` 
1. `'FIML'` - Full Information Maximum Likelihood;
2. `'REML'` - Restricted Maximum Likelihood.
- `ModelEffects`
1. `'ML'` - Maximum Likelihood;
2. `'REML'` - Restricted Maximum Likelihood.

For example:

In [25]:
m = Model(desc)
print(m.fit(data, obj='ULS'))
m.inspect()

Name of objective: ULS
Optimization method: SLSQP
Optimization successful.
Optimization terminated successfully
Objective value: 6.014
Number of iterations: 30
Params: 0.220 0.796 0.358 0.950 1.395 0.000 7.432 6.839 16.070 8.947 8.632 9.051 2.523

    lval  op  rval      Estimate  Std. Err   z-value   p-value
0   eta2   ~  eta1  1.394963e+00  0.744385  1.873981  0.060933
1     y1   ~  eta1  1.000000e+00         -         -         -
2     y2   ~  eta1  2.200319e-01  0.252588  0.871109  0.383695
3     y3   ~  eta1  7.963104e-01  0.315811  2.521478  0.011686
4     y4   ~  eta2  1.000000e+00         -         -         -
5     y5   ~  eta2  3.583617e-01  0.198462  1.805693  0.070966
6     y6   ~  eta2  9.501895e-01   0.34289  2.771122  0.005586
7   eta2  ~~  eta2  1.056526e-16  2.520223       0.0       1.0
8   eta1  ~~  eta1  2.523207e+00  1.559162  1.618309  0.105596
9     y6  ~~    y6  7.432279e+00  1.880004  3.953331  0.000077
10    y3  ~~    y3  6.838632e+00  1.226116  5.577478       0.0
11    y4  ~~    y4  1.607024e+01  2.903285  5.535192       0.0
12    y1  ~~    y1  8.947062e+00  1.732525  5.164175       0.0
13    y5  ~~    y5  8.631615e+00  1.283918   6.72287       0.0
14    y2  ~~    y2  9.050878e+00  1.291789  7.006468       0.0